version: '3.4'
services:
  qlogd:
    build: ./qlogd
    volumes:
      - source: ./qlogd
        target: /code
        type: bind
      - "bot-logs:/var/app"
    environment:
      - BROKER_PORT=1883

  cli:
    build: ./cli
    volumes:
      - source: ./cli
        target: /code
        type: bind
    environment:
      - BROKER_PORT=1883

  broker:
    image: cyrilix/rabbitmq-mqtt:3.6
    ports:
      - "15672:15672"
      - "1883:1883"
      - "8883:8883"
      - "4369:4369"
      - "5671:5671"
      - "5672:5572"
      - "25672:25672"

  db:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=Development
    volumes:
      - "db-data:/data/db"

  web:
    build: ./web
    volumes:
      - source: ./web
        target: /web
        type: bind
      - "web-logs:/var/log"
    ports:
      - "5000:5000"
    dns:
      - 8.8.8.8

volumes:
  db-data:
  bot-logs:
  web-logs:
